# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-24 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('url_completa', models.CharField(max_length=100, unique=True)),
                ('url_scheme', models.CharField(max_length=5)),
                ('url_acortada', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
